### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by blankbrass** [Gitko01/Hullabaloo#1]
[17:11:35] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hullabaloo'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.4-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/itemgroup/FabricItemGroupBuilder
	at net.gitko.hullabaloo.item.ModItemGroup.<clinit>(ModItemGroup.java:11) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.gitko.hullabaloo.item.ModItems.initItems(ModItems.java:80) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.gitko.hullabaloo.Hullabaloo.onInitialize(Hullabaloo.java:48) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.gitko.hullabaloo.item.ModItemGroup.<clinit>(ModItemGroup.java:11) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.gitko.hullabaloo.item.ModItems.initItems(ModItems.java:80) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.gitko.hullabaloo.Hullabaloo.onInitialize(Hullabaloo.java:48) ~[hullabaloo-1.0.0-mc1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
	... 8 more

**Comment by ChacePratt** [comment]
Interesting, I’ll look into this

**Comment by ChacePratt** [comment]
It seems you are trying to load Hullabaloo 1.19.2 on a Fabric 1.19.4 server - download this [version ](https://github.com/Gitko01/Hullabaloo/releases/download/v1.0.0/hullabaloo-1.0.0-mc1.19.4.jar) and replace the old Hullabaloo jar.
